services:
  web:
    build: .
    environment:
      - CORS_ORIGIN='*'
      - REDIS_URL=redis://redis
      - AUTH_KEY=auth.docker
      - DATABASE_URL=mongodb+srv://user:password@host/portfolio?retryWrites=true&w=majority&appName=Cluster0
      - IMAGEKIT_PUBLIC_KEY=
      - IMAGEKIT_PRIVATE_KEY=
      - IMAGEKIT_URL_ENDPOINT=
      - IMAGEKIT_FOLDER=
      - SMTP_URL=
    ports:
      - 3001:3001
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
